### ISSUE TITLE
Proof of Concept Milestone

### ISSUE THREAD

**Issue by AnirudhVyas** [AntarYoga/AntarAssessment#2]
**POC Milestone for MVP**
- [ ]  Simple user sign up - Not much attention to security.
- [ ]  Capability  to create a new self assessment and record it on sql-lite db.
- [ ] Capability to schedule assessments at fixed frequency:
         - [ ] Daily
         - [ ] Weekly
         - [ ] Monthly
         - [ ] Quarterly
- [ ]  Capability to see past self assessments.
