### ISSUE TITLE
Release Candidate Milestone

### ISSUE THREAD

**Issue by AnirudhVyas** [AntarYoga/AntarAssessment#3]
**RC Milestone**

Other than _POC_ these are additional items that are needed:
- [ ] Single sign on using facebook, google.
- [ ] Summary Stats for each user.
- [ ] Teacher/Mentor special login and signup - allows mentors to see their `students` progress so as to speak.
